# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

# Times in UTC
production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  deliver_submission_links:
    class: DeliverSubmissionLinksJob
    schedule: every tuesday at 1pm
  check_and_deliver_standings_thursday:
    class: DeliverStandingsJob
    schedule: '*/15 2-4 * * 5'
  check_and_deliver_standings_sunday:
    class: DeliverStandingsJob
    schedule: '*/15 20-23 * * 0'
  check_and_deliver_standings_sunday_2:
    class: DeliverStandingsJob
    schedule: '*/15 0-5 * * 1'
  check_and_deliver_standings_monday:
    class: DeliverStandingsJob
    schedule: '*/15 2-4 * * 2'
  schedule_hash_delivery:
    class: ScheduleHashDeliveryJob
    schedule: every thursday at 2pm
